export const DUMMY_EXPENSES = [
  {
    id: 'e5',
    description: 'Fashion Tees',
    amount: 18.59,
    category: 'Transaction',
    date: new Date('2022-02-18'),
    name: 'Foldsack No. 1 Backpack, Fits 15 Laptops',
    description: 'Occasion',
  },
  {
    id: '13',
    name: 'Mens Casual Premium Slim Fit',
    amount: '59.9922',
    category: 'Transaction',
    date: '2023-01-18',
    description: 'abric is soft',
  },
  {
    id: '14',
    name: 'Mens Cotton Jacket',
    amount: '5119.9922',
    category: 'Transaction',
    date: '2023-06-22',
    description: 'Boat Neck V',
  },
  {
    id: 'e52',
    description: 'Short Sleeve',
    amount: 18.59,
    category: 'Transaction',
    date: new Date('2022-02-18'),
    name: 'USA or Imported',
    description: 'Legends Naga Gold',
  },
  {
    id: 'e51',
    description: 'Womens T Shirt',
    amount: 18.59,
    category: 'Income',
    date: new Date('2022-02-18'),
    name: 'USA',
    description: 'White Gold Plated Princess',
  },
  {
    id: '132',
    name: 'Casual Cotton',
    amount: '259.9922',
    category: 'Income',
    date: '2023-01-9',
    description: 'Rose Gold Plated Stainless Steel',
  },
  {
    id: '141',
    name: 'A Short Sleeve',
    amount: '5119.9922',
    category: 'Expense',
    date: '2023-02-8',
    description: 'SSD PLUS 1TB Internal SSD ',
  },
  {
    id: '5',
    description: 'Solid book',
    amount: 130.59,
    category: 'Income',
    date: new Date('2022-04-28'),
    name: 'Casual Cotton',
    description: 'Power 256GB SSD 3D NAND A55 SLC Cache',
  },
  {
    id: '131',
    name: 'Lock and Love',
    amount: 340.9922,
    category: 'Income',
    date: '2023-01-18',
    description: 'Gaming Drive Works with Playstation',
  },
  {
    id: '142',
    name: 'A bank',
    amount: '51219.9922',
    category: 'Expense',
    date: '2023-01-18',
    description: 'IPS Ultra-Thin',
  },
  {
    id: 'e52q',
    description: 'clothing',
    amount: 235.59,
    category: 'Expense',
    date: new Date('2022-05-18'),
    name: 'Lightweight fabric',
    description: 'Samsung 49-Inch CHG90',
  },
  {
    id: 'e521',
    description: 'electronics',
    amount: 18.59,
    category: 'Expense',
    date: new Date('2022-06-18'),
    name: 'stretch for comfort',
    description: 'Curved Gaming Monitor',
  },
];

export const sliderImages = [
  'https://img.etimg.com/thumb/msid-93051525,width-1070,height-580,imgsize-2243475,overlay-economictimes/photo.jpg',
  'https://images-eu.ssl-images-amazon.com/images/G/31/img22/Wireless/devjyoti/PD23/Launches/Updated_ingress1242x550_3.gif',
  'https://images-eu.ssl-images-amazon.com/images/G/31/img23/Books/BB/JULY/1242x550_Header-BB-Jul23.jpg',
];
