export const DUMMY_EXPENSES = [
  {
    id: 'e5',
    description: 'Another book',
    amount: 18.59,
    category: 'Transaction',
    date: new Date('2022-02-18'),
    name: 'A pair',
    description: 'A pair of assqww',
  },
  {
    id: '13',
    name: 'A pair',
    amount: '59.9922',
    category: 'Transaction',
    date: '2023-01-18',
    description: 'A pair of assqww',
  },
  {
    id: '14',
    name: 'A pairasas',
    amount: '5119.9922',
    category: 'Transaction',
    date: '2023-01-18',
    description: 'A of assqww',
  },
  {
    id: 'e52',
    description: 'Another book',
    amount: 18.59,
    category: 'Transaction',
    date: new Date('2022-02-18'),
    name: 'A pair',
    description: 'A pair of assqww',
  },
  {
    id: 'e51',
    description: 'Another book',
    amount: 18.59,
    category: 'Income',
    date: new Date('2022-02-18'),
    name: 'A pair',
    description: 'A pair of assqww',
  },
  {
    id: '132',
    name: 'A pair',
    amount: '259.9922',
    category: 'Income',
    date: '2023-01-9',
    description: 'A pair of assqww',
  },
  {
    id: '141',
    name: 'A pairasas',
    amount: '5119.9922',
    category: 'Income',
    date: '2023-02-8',
    description: 'A of assqww',
  },
  {
    id: '5',
    description: 'Another book',
    amount: 118.59,
    category: 'Income',
    date: new Date('2022-04-28'),
    name: 'A pair',
    description: 'A pair of new',
  },
  {
    id: '131',
    name: 'A pair',
    amount: '519.9922',
    category: 'Income',
    date: '2023-01-18',
    description: 'A pair of assqww',
  },
  {
    id: '142',
    name: 'A bank',
    amount: '51219.9922',
    category: 'Income',
    date: '2023-01-18',
    description: 'A of assqww',
  },
  {
    id: 'e52q',
    description: 'Another book',
    amount: 18.59,
    category: 'Income',
    date: new Date('2022-05-18'),
    name: 'A pair',
    description: 'A pair of assqww',
  },
  {
    id: 'e521',
    description: 'Another book',
    amount: 18.59,
    category: 'Expense',
    date: new Date('2022-06-18'),
    name: 'A pair',
    description: 'A pair of assqww',
  },
  {
    id: '1312',
    name: 'A as pair',
    amount: '2519.9922',
    category: 'Expense',
    date: '2023-08-9',
    description: 'A pair of assqww',
  },
  {
    id: '1141',
    name: 'A pairasas',
    amount: '51119.9922',
    category: 'Expense',
    date: '2023-02-8',
    description: 'A of assqww',
  },
  {
    id: '51',
    description: ' book',
    amount: 1128.59,
    category: 'Expense',
    date: new Date('2022-09-8'),
    name: 'A pair',
    description: 'A pair of new',
  },
];
export const sliderImages = [
  'https://img.etimg.com/thumb/msid-93051525,width-1070,height-580,imgsize-2243475,overlay-economictimes/photo.jpg',
  'https://images-eu.ssl-images-amazon.com/images/G/31/img22/Wireless/devjyoti/PD23/Launches/Updated_ingress1242x550_3.gif',
  'https://images-eu.ssl-images-amazon.com/images/G/31/img23/Books/BB/JULY/1242x550_Header-BB-Jul23.jpg',
];
